adminUser:
  password: vault:vs-pr-200-62arc/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jenkins-x@googlegroups.com
  token: vault:vs-pr-200-62arc/pipelineUser:token
  username: jenkins-x-bot-test
prow:
  hmacToken: vault:vs-pr-200-62arc/prow:hmacToken
segmentWriteKey: vault:vs-pr-200-62arc:segmentWriteKey
